services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: node_esmodule_starter_template
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/node_esmodule_starter_template
    ports:
      - 3000:3000

volumes:
  db-data:
