name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm i
      - name: Wait for Postgres
        run: until pg_isready -h localhost -p 5432; do sleep 1; done
      - name: Run migrations & seeders
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASS: 123456
          DB_NAME: node_esmodule_starter_template
          DATABASE_URL: postgres://postgres:123456@localhost:5432/node_esmodule_starter_template
        run: npm run migrate:seed
      - name: Run lints and tests
        run: npm run ci
